---
version: "2.1"

#GITHUB=https://github.com/linuxserver/docker-heimdall
#DOCKERHUB=https://hub.docker.com/r/linuxserver/heimdall

networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge

services:
  heimdall:
    image: linuxserver/heimdall:version-2.2.2
    container_name: Heimdall
    restart: always
    networks:
      - t2_proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - UMASK=022 #optional (Default = 022)
    volumes:
      - $DOCKER_DIR/heimdall/app:/config
    ports:
      - $HEIMDALL_PORT:80
      - $HEIMDALL_SECURE_PORT:443
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.heimdall-rtr.entrypoints=https"
      - "traefik.http.routers.heimdall-rtr.rule=Host(`heimdall.$DOMAINNAME`)"
      - "traefik.http.routers.heimdall-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.heimdall-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.heimdall-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      - "traefik.http.routers.heimdall-rtr.middlewares=chain-authelia@file" # Authelia
      ## HTTP Services
      - "traefik.http.routers.heimdall-rtr.service=heimdall-svc"
      - "traefik.http.services.heimdall-svc.loadbalancer.server.port=80"