version: "3"

#GITHUB=https://github.com/pi-hole/docker-pi-hole
#DOCKERHUB=https://hub.docker.com/r/pihole/pihole

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: Pihole
    image: pihole/pihole:v5.8.1
    restart: always
    network_mode: host
    # ports:
      # - "53:53/tcp"
      # - "53:53/udp"
      # - "67:67/udp"
      # - "80:80/tcp"
    environment:
      ADMIN_EMAIL: '$EMAIL'
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      PIHOLE_DNS_: '127.0.0.1#5053'
      WEB_PORT: $PIHOLE_WEB_PORT
    # Volumes store your data between container upgrades
    volumes:
      - $DOCKER_DIR/pihole/app/etc-pihole:/etc/pihole/
      - $DOCKER_DIR/pihole/app/etc-dnsmasq.d:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN