---
version: "3"
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: HomeAssistant
    network_mode: host
    volumes:
      - $DOCKER_DIR/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
     - UID=$PUID
     - GID=$PGID
     - TZ=$TZ
    restart: always