version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge

########################### SERVICES
services:
# All services / apps go below this line

# Traefik 2 - Reverse Proxy
  traefik:
    container_name: Traefik
    image: traefik:2.4.8
    restart: unless-stopped
    command: # CLI arguments https://doc.traefik.io/traefik/reference/static-configuration/cli/
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
        # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      - --api=true  # Enable api/dashboard (Default: false)
      - --api.dashboard=true
      # - --api.insecure=true  # Activate API directly on the entryPoint named traefik. (Default: false)
      # - --serversTransport.insecureSkipVerify=true  # Disable SSL certificate verification. (Default: false)
      - --log=true
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true  # Enable Docker backend with default settings. (Default: false)
      # - --providers.docker.watch=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME`)
      - --providers.docker.exposedByDefault=false  #  Expose containers by default. (Default: true)
      - --providers.docker.network=t2_proxy  # Default docker network used
      - --providers.docker.swarmMode=false  # Use Docker on Swarm Mode. (Default: false)
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
      # - --providers.file.filename=/path/to/file # Load dynamic configuration from a file.
      - --providers.file.watch=true # Only works on top level files in the rules folder
      
      ## CloudFlare settings
      # - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53

    networks:
      t2_proxy:
        ipv4_address: $TRAEFIK_IP  # You can specify a static IP
    security_opt:
      - no-new-privileges:true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - $DOCKER_DIR/traefik2/app/rules:/rules 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DOCKER_DIR/traefik2/app/acme/acme.json:/acme.json 
      - $DOCKER_DIR/traefik2/app/traefik.log:/traefik.log 
      - $DOCKER_DIR/shared:/shared
    environment:
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
      # - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare" # Comment out this line after first run of traefik to force the use of wildcard certs
      - "traefik.http.routers.traefik-rtr.tls.domains[0].main=$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.$DOMAINNAME"
#      - "traefik.http.routers.traefik-rtr.tls.domains[1].main=$SECONDDOMAINNAME" # Pulls main cert for second domain
#      - "traefik.http.routers.traefik-rtr.tls.domains[1].sans=*.$SECONDDOMAINNAME" # Pulls wildcard cert for second domain
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file"

      ## Security header middleware options if NOT using the 'middlewares-secure-headers@file' option
      # - "traefik.http.middlewares.traefik-headers.headers.accesscontrolallowmethods=GET, OPTIONS, PUT"
      # - "traefik.http.middlewares.traefik-headers.headers.accesscontrolalloworiginlist=https://$DOMAINNAME"
      # - "traefik.http.middlewares.traefik-headers.headers.accesscontrolmaxage=100"
      # - "traefik.http.middlewares.traefik-headers.headers.addvaryheader=true" 
      # - "traefik.http.middlewares.traefik-headers.headers.allowedhosts=traefik.$DOMAINNAME" 
      # - "traefik.http.middlewares.traefik-headers.headers.hostsproxyheaders=X-Forwarded-Host"
      # - "traefik.http.middlewares.traefik-headers.headers.sslredirect=true"
      # - "traefik.http.middlewares.traefik-headers.headers.sslhost=traefik.$DOMAINNAME" 
      # - "traefik.http.middlewares.traefik-headers.headers.sslforcehost=true"
      # - "traefik.http.middlewares.traefik-headers.headers.sslproxyheaders.X-Forwarded-Proto=https"
      # - "traefik.http.middlewares.traefik-headers.headers.stsseconds=63072000"
      # - "traefik.http.middlewares.traefik-headers.headers.stsincludesubdomains=true"
      # - "traefik.http.middlewares.traefik-headers.headers.stspreload=true"
      # - "traefik.http.middlewares.traefik-headers.headers.forcestsheader=true"
      # - "traefik.http.middlewares.traefik-headers.headers.framedeny=true"
      ## - "traefik.http.middlewares.traefik-headers.headers.customframeoptionsvalue=SAMEORIGIN" # This option overrides FrameDeny
      # - "traefik.http.middlewares.traefik-headers.headers.contenttypenosniff=true"
      # - "traefik.http.middlewares.traefik-headers.headers.browserxssfilter=true"
      ## - "traefik.http.middlewares.traefik-headers.headers.contentsecuritypolicy=frame-ancestors 'none'; object-src 'none'; base-uri 'none';"
      # - "traefik.http.middlewares.traefik-headers.headers.referrerpolicy=same-origin"
      # - "traefik.http.middlewares.traefik-headers.headers.featurepolicy=camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
      # - "traefik.http.middlewares.traefik-headers.headers.customresponseheaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex,"

  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  authelia:
    container_name: Authelia
    # image: authelia/authelia:latest
    image: authelia/authelia:4.21.0
    restart: always
    networks:
      - t2_proxy
    depends_on:
      # - authelia-db
      - redis
    volumes:
      - $DOCKER_DIR/authelia/app:/config
    ports:
      - $AUTHELIA_PORT:$AUTHELIA_PORT
    environment:
      - TZ=$TZ
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/authelia_session_redis_password
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
      # - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_session_redis_password
      - authelia_storage_mysql_password
      # - authelia_notifier_smtp_password
      - authelia_duo_api_secret_key
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAINNAME`)"
      - "traefik.http.routers.authelia-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=$AUTHELIA_PORT"
      
  # authelia-db:
    # image: 'mariadb:latest'
    # container_name: 'Authelia_DB'
    # restart: always
    # networks:
      # - t2_proxy
    # ports:
      # - '$AUTHELIA_DB_PORT:3306'
    # environment:
      # - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/authelia_mysql_root_password
      # - MYSQL_DATABASE="authelia"
      # - MYSQL_USER="authelia"
      # - MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
    # secrets:
      # - authelia_mysql_root_password
      # - authelia_storage_mysql_password
    # volumes:
      # - $DOCKER_DIR/authelia/db:/var/lib/mysql

  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: Redis
    restart: always
    networks:
      - t2_proxy
    environment:
      # ALLOW_EMPTY_PASSWORD=yes # only recommended only for development.
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD_FILE=/run/secrets/authelia_session_redis_password
    secrets:
      - authelia_session_redis_password
    ports:
      - '$REDIS_PORT:$REDIS_PORT'
    volumes:
      - $DOCKER_DIR/redis/app:/bitnami/redis/data'

##### SECRETS

secrets:
  authelia_jwt_secret:
    file: $SECRETS_DIR/authelia/app/authelia_jwt_secret
  authelia_session_secret:
    file: $SECRETS_DIR/authelia/app/authelia_session_secret
  authelia_session_redis_password:
    file: $SECRETS_DIR/redis/app/redis_password
  # authelia_notifier_smtp_password:
    # file: $SECRETS_DIR/authelia/app/authelia_notifier_smtp_password
  authelia_duo_api_secret_key:
    file: $SECRETS_DIR/authelia/app/authelia_duo_api_secret_key
  authelia_storage_mysql_password:
    file: $SECRETS_DIR/authelia/db/authelia_storage_mysql_password
  authelia_mysql_root_password:
    file: $SECRETS_DIR/authelia/db/authelia_mysql_root_password