---
version: "3"

#GITHUB=https://github.com/henrywhitaker3/Speedtest-Tracker
#DOCKERHUB=https://hub.docker.com/r/henrywhitaker3/speedtest-tracker

networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge

services:
  app:
    image: henrywhitaker3/speedtest-tracker:latest
    container_name: Speedtest
    networks:
      - t2_proxy
    restart: always
    volumes:
      - $DOCKER_DIR/speedtest/app:/config
    ports:
      - $SPEEDTEST_PORT:80
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - OOKLA_EULA_GDPR=true
      - AUTH=true
      # - SLACK_WEBHOOK=
      # - TELEGRAM_BOT_TOKEN=
      # - TELEGRAM_CHAT_ID=
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.speedtest-rtr.entrypoints=https"
      - "traefik.http.routers.speedtest-rtr.rule=Host(`speedtest.$DOMAINNAME`, `www.speedtest.$DOMAINNAME`)"
      - "traefik.http.routers.speedtest-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.speedtest-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.speedtest-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      - "traefik.http.routers.speedtest-rtr.middlewares=chain-authelia@file" # 2FA Authelia
      ## HTTP Services
      - "traefik.http.routers.speedtest-rtr.service=speedtest-svc"
      - "traefik.http.services.speedtest-svc.loadbalancer.server.port=80"